openapi: 3.0.0
info:
  version: '1.0'
  title: holder-view-configurations
  description: An APi that defines how to retrieve the api configuration data for a holder
servers:
  - url: 'http://localhost:3000'
paths:
  /holdername-view-configurations:
    get:
      summary: Your GET endpoint
      description: |
        An end point to return the configuration data for registerd pension data providers.
      operationId: get-holdername-view-configurations
      parameters:
        - $ref: '#/components/parameters/holdername_guid'
        - $ref: '#/components/parameters/X-Request-ID'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  holder_view_configurations:
                    type: array
                    description: The holderConfiguration data identfied based on the passed parameters
                    minItems: 1
                    items:
                      type: object
                      properties:
                        holdername_guid:
                          type: string
                          description: The base url for the pension-illustrations API hosted by the holder.
                          format: uuid
                          example: 550e8400-e29b-41d4-a716-446655440000
                        veiw_data_url:
                          type: string
                          description: 'The full path that can be used to make a GET view-data request, including resource name.'
                          format: uri
                          example: 'https://exampleprovider/pensiondataprovider/view-data'
                      required:
                        - holdername_guid
                        - veiw_data_url
              examples:
                Example 1:
                  value:
                    holder_view_configurations:
                      - holdername_guid: 550e8400-e29b-41d4-a716-446655440000
                        veiw_data_url: 'https://exampleprovider/pensiondataprovider/view-data'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
        '502':
          description: Bad Gateway
        '503':
          description: Service Unavailable
        '504':
          description: Gateway Timeout
      servers:
        - url: 'http://localhost:3000'
components:
  parameters:
    holdername_guid:
      name: holdername_guid
      in: query
      description: 'The guid identifying the holdername whose view configuration is required '
      required: false
      schema:
        type: string
        format: uuid
        pattern: '^(?:[0-9a-fA-F]){8}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){12}\}{0,1}$'
        minLength: 36
        maxLength: 36
        example: 728f9722-88c1-42f3-965a-d2faab8967e8
    X-Request-ID:
      name: X-Request-ID
      in: header
      description: A unique correlation id
      required: true
      schema:
        type: string
        format: uuid
        example: 35cfcfb0-d98d-451f-83f1-e59933078555