openapi: 3.0.0
info:
  version: '1.0'
  title: jwk_uri
  description: This API defines an endpoint from which public keys can be retrieved.
servers:
  - url: 'http://localhost:3000'
paths:
  /jwk_uri:
    get:
      summary: Your GET endpoint
      operationId: getJwkUri
      responses:
        '200':
          $ref: '#/components/responses/200-Success'
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
        '502':
          description: Bad Gateway
        '503':
          description: Service Unavailable
        '504':
          description: Gateway Timeout
      servers:
        - url: 'http://localhost:3000'
components:
  responses:
    200-Success:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              keys:
                type: array
                items:
                  type: object
                  properties:
                    kty:
                      type: string
                      description: |-
                        Specifies the type of cryptographic key. Common values include RSA for RSA keys and EC for elliptic curve keys.
                        See https://datatracker.ietf.org/doc/html/rfc7517#section-4.1.
                    kid:
                      type: string
                      description: |-
                        A unique identifier for the key, used to select the correct key when validating a JWT. This kid should match the kid value in the JWT header.
                        See https://datatracker.ietf.org/doc/html/rfc7517#section-4.5
                    'n':
                      type: string
                      description: |
                        The RSA public modulus, in base64url-encoded format.
                    e:
                      type: string
                      description: 'The RSA public exponent, also in base64url-encoded format.'
                    x5t#S256:
                      type: string
                      description: 'See, https://datatracker.ietf.org/doc/html/rfc7517#section-4.9'
                    x5c:
                      type: string
                      description: 'See https://datatracker.ietf.org/doc/html/rfc7517#section-4.7'
                  required:
                    - kty
                    - kid
                    - 'n'
                    - e
          examples:
            Example 1:
              value:
                keys:
                  - kty: RSA
                    kid: 1b94c
                    alg: RS256
                    use: sig
                    'n': tK9-bD4fJhJ1Dl6eK5Fl_cYg0yHl...
                    e: AQAB
                  - kty: RSA
                    kid: 4c9f1
                    alg: RS256
                    use: sig
                    'n': oahUIX6rWtkEXiBfnnzR9eApRG_t0...
                    e: AQAB