openapi: 3.0.0
info:
  version: '1.0'
  title: MaPS Pensions Retrieval Records
  description: This service allows a client to retrieve pensions retrieval records for a pension owner session.
  termsOfService: 'https://maps.org.uk/en/about-us/terms-and-conditions#'
  contact:
    name: General Enquires
    url: 'https://maps.org.uk/en/about-us/contact-us'
    email: contact@maps.org.uk
  license:
    url: 'https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/'
    name: Government API License
servers:
  - url: 'http://localhost:3000'
    description: LocalTest
paths:
  /pensions-retrieval-records:
    get:
      tags:
        - Pensions Data
      summary: Get Pensions Retrieval Record
      description: |-
        Get the pensions retrieval record that contains the information on the state of a process to 
        retrieve the pensions data for a user session from the PDP ecosystem
      operationId: get-pensions-retrieval-record-for-pension-owner-session
      parameters:
        - name: userSessionId
          in: header
          description: The unique id of pension owner session as issued by the requesting system
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/mhpdCorrelationId'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pensionsRetrievalRecord'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
        '502':
          description: Bad Gateway
        '503':
          description: Service Unavailable
        '504':
          description: Gateway Timeout
      security: []
      servers:
        - url: 'http://localhost:3000'
          description: LocalTest
tags:
  - name: Pensions Data
    description: Pensions Data Retrieval
components:
  parameters:
    mhpdCorrelationId:
      name: mhpdCorrelationId
      in: header
      description: Id to track the progress of a process throughout the the mhpd application
      required: false
      schema:
        type: string
        format: uuid
        pattern: '^(?:[0-9a-fA-F]){8}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){12}\}{0,1}$'
        minLength: 36
        maxLength: 36
  schemas:
    pensionsRetrievalRecord:
      type: object
      title: pensionsRetrievalRecord
      properties:
        id:
          type: string
          description: |
            The unique Id of the pension retrieval record
          format: uuid
          minLength: 36
          maxLength: 38
        userSessionId:
          type: string
          description: The unique id of the user session under which the pensions are being retrieved.
          format: uuid
          minLength: 36
          maxLength: 36
        iss:
          type: string
          description: |
            The unique identifier of the system, registered with the CDA, that needs permission from the pension owner to access the pension data.
          minLength: 1
          maxLength: 200
        jobStartTimestamp:
          type: string
          description: The utc millisecond timestamp for when the retrieval process was initiated.
          format: date-time
          minLength: 23
          maxLength: 23
        peisRpt:
          type: string
          description: The RPT token that provides access the peis collection denoted by the peisId
          pattern: '^([a-zA-Z0-9_=]+)\.([a-zA-Z0-9_=]+)\.([a-zA-Z0-9_\-\+\/=]*)'
        peiRetrievalComplete:
          type: boolean
          description: Indicator denoting if the peis represent the complete set of pei identified for the pension owner at a point in time.
        peisId:
          type: string
          description: The base url where the CDA peis API is located.
          format: uuid
          minLength: 36
          maxLength: 36
        peiData:
          type: array
          description: |-
            The list of pei data retrieved for the cdaUserGuid and userSessionId.
            An empty array indicates that no PeIs have yet been retrieved.
          items:
            $ref: '#/components/schemas/eIData'
      required:
        - id
        - userSessionId
        - iss
        - jobStartTimestamp
        - peiRetrievalComplete
        - peisId
        - peiData
    eIData:
      type: object
      title: eIData
      description: Data for a retrieved PeI
      properties:
        pei:
          type: string
          description: "The PeI. \_\n\nThis must be two 36 character GUIDs separated by a colon.\n\nThe first GUID is a holder-name GUID which is a unique identifier for the holder of the pensions data as known to the CDA\n\nThe second GUID is a unique identifier for the pensions data as known by the resource holder."
          pattern: '^(?:\{{0,1}(?:[0-9a-fA-F]){8}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){12}\}{0,1}?:\{{0,1}(?:[0-9a-fA-F]){8}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){12}\}{0,1})$'
          minLength: 73
          maxLength: 73
        description:
          type: string
          description: |-
            The human readable description of the title of the pension scheme that the asset is associated with.
            Typically the scheme name
          minLength: 1
          maxLength: 150
        retrievalStatus:
          type: string
          enum:
            - NEW
            - RETRIEVAL_REQUESTED
            - RETRIEVAL_COMPLETE
            - RETRIEVAL_FAILED
          description: |-
            The current status of the retrieval of the pension arrangement data associated identified by the PeI.
            - `NEW` - retrieval of the associated pension data has not be requested
            - `RETRIEVAL_REQUESTED` - retrieval of the associated pension data has not be requested
            - `RETRIEVAL_COMPLETE` - the retrieval of the pension data for the has been completed. Albeit that the data may not all be available
            - `RETRIEVAL_FAILED` - the retrieval of the pension data failed and will not be retried until later.
        retrievalRequestedTimestamp:
          type: string
          description: The utc millisecond timestamp for the last time that a request was made to retrieve the pension arrangement data associated identified by the PeI.
          format: date-time
          minLength: 23
          maxLength: 23
      required:
        - pei
        - description
        - retrievalStatus