openapi: 3.0.0
info:
  version: '1.0'
  title: MaPS-Cda-Rpts
servers:
  - url: 'http://localhost:3000'
paths:
  /rpts:
    post:
      summary: Retrieve an RPT
      operationId: post-pei_retrieval_details
      parameters:
        - $ref: '#/components/parameters/mhpdCorrelationId'
      requestBody:
        $ref: '#/components/requestBodies/rptRequest'
      responses:
        '200':
          $ref: '#/components/responses/rptResponse'
      servers:
        - url: 'http://localhost:3000'
components:
  parameters:
    mhpdCorrelationId:
      name: mhpdCorrelationId
      in: header
      description: Id to track the progress of a process throughout the the mhpd application
      required: false
      schema:
        type: string
        format: uuid
        pattern: '^(?:[0-9a-fA-F]){8}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){12}\}{0,1}$'
        minLength: 36
        maxLength: 36
  requestBodies:
    rptRequest:
      content:
        application/json:
          schema:
            type: object
            properties:
              ticket:
                type: string
                description: A JWT PMT
                pattern: '^([a-zA-Z0-9_=]+)\.([a-zA-Z0-9_=]+)\.([a-zA-Z0-9_\-\+\/=]*)'
              rqp:
                type: string
                description: An RQP token representing the application and user on who's behalf a request will be made
                pattern: '^([a-zA-Z0-9_=]+)\.([a-zA-Z0-9_=]+)\.([a-zA-Z0-9_\-\+\/=]*)'
              as_uri:
                type: string
                description: |
                  The location of of the authorisation service.
            required:
              - ticket
              - rqp
              - as_uri
  responses:
    rptResponse:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              rpt:
                type: string
                description: |
                  The base url for the API to manages peis resources
                pattern: '^([a-zA-Z0-9_=]+)\.([a-zA-Z0-9_=]+)\.([a-zA-Z0-9_\-\+\/=]*)'
            required:
              - rpt
      headers:
        mhpdCorrelationId:
          schema:
            type: string
            format: uuid
            pattern: '^(?:[0-9a-fA-F]){8}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){4}-(?:[0-9a-fA-F]){12}\}{0,1}$'
            minLength: 36
            maxLength: 36
            example: e50cb5e0-f4db-4187-b970-e89e42ebea16
          description: Id to track the progress of a process throughout the the mhpd application