openapi: 3.0.0
info:
  version: '1.0'
  title: peis
  description: |
    This API defines endpoint to enable a dashboard to retrieve a summary of the peis currently registered with the CDA.
    Currently access to the peis is governed by UMA enforced on each call meaning only peis relating to a particular owner can be retrieved in a call.
servers:
  - url: 'http://localhost:3000'
paths:
  '/peis/{peis_id}':
    get:
      summary: Your GET endpoint
      description: Retrive a summary of the registered peis associated with a particular owner
      operationId: get-peis
      parameters:
        - $ref: '#/components/parameters/X-Request-ID'
        - name: peis_id
          in: path
          description: A unique id of the collection of peis relating to cdaUser
          required: true
          schema:
            type: string
            format: uuid
            example: 74252e4f-d9fd-417d-8024-3847a024bd8e
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              examples:
                Example 1:
                  value:
                    peiList:
                      - pei: '728f9722-88c1-42f3-965a-d2faab8967e8:26d93ebc-0dfd-43c0-bfee-2b8f8ad7a742'
                        description: My Pension Scheme
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
          headers:
            WWW-Authenticate:
              schema:
                type: string
                example: 'realm="PensionDashboard", as_uri="https://as.pdp.com", ticket="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.cThIIoDvwdueQB468K5xDc5633seEFoqwxjF_xSJyQQ"'
              description: "The WWW-authenticate header, see https://datatracker.ietf.org/doc/html/rfc7235?utm_source=localhost%3A8080#page-7:~:text=framework.%0A%0A4.1.-,WWW%2DAuthenticate,-The%20%22WWW%2DAuthenticate,\_containing the following claims:realm, in this scenario the returned realm must always be  \"PensionDashboard\".  as_uri, the path to the authorise endpoint.  ticket, the PMT provided as a JWT token.  The dashbaord does not need to interpret this ticket."
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
        '502':
          description: Bad Gateway
        '503':
          description: Service Unavailable
        '504':
          description: Gateway Timeout
      security:
        - rpt: []
      servers:
        - url: 'http://localhost:3000'
components:
  parameters:
    X-Request-ID:
      name: X-Request-ID
      in: header
      description: A unique correlation id
      required: true
      schema:
        type: string
        format: uuid
        example: 35cfcfb0-d98d-451f-83f1-e59933078555
  securitySchemes:
    rpt:
      type: http
      scheme: bearer