---
openapi: 3.0.0
info:
  title: view-data
  description: |
    An API for a service to be hosted by Pension Data Providers within the PDP ecosystem to enable retrieval of the details of a pension and pension illustrations associated with an asset_guid.
  version: "1.0"
servers:
- url: http://localhost:3000
tags:
- name: retrieve-pension-and-pension-illustration-details
  description: Retrieve the details of a pension along with illustrations of the retirement benefits
paths:
  /view-data/{asset_guid}:
    get:
      tags:
      - retrieve-pension-and-pension-illustration-details
      summary: Retrieve the pension and pension illustration details for a pension known to the Pension Data Provider by the asset_guid.
      description: Retrieve the pension details associated with a particular asset_guid for a particular user.
      operationId: get-pension-and-pension-illlustration-details
      parameters:
      - name: scope
        in: query
        description: The scope that the request for details is being made in
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: owner
          enum:
          - owner
      - name: asset_guid
        in: path
        description: The unique id of a pension as known to the Pension Data Provider
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: X-Request-ID
        in: header
        description: A unique correlation id
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
          example: 35cfcfb0-d98d-451f-83f1-e59933078555
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
          headers:
            WWW-Authenticate:
              description: "The WWW-authenticate header, see https://datatracker.ietf.org/doc/html/rfc7235?utm_source=localhost%3A8080#page-7:~:text=framework.%0A%0A4.1.-,WWW%2DAuthenticate,-The%20%22WWW%2DAuthenticate,\_containing the following claims: realm, in this scenario the returned realm must always be  \"PensionDashboard\".  as_uri, the path to the authorise endpoint.  ticket, the PMT provided as a JWT token.  The dashboard does not need to interpret this ticket."
              style: simple
              explode: false
              schema:
                type: string
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
        "502":
          description: Bad Gateway
        "503":
          description: Service Unavailable
        "504":
          description: Gateway Timeout
      security:
      - rpt: []
      servers:
      - url: http://localhost:3000
components:
  schemas:
    inline_response_200:
      required:
      - view_data_token
      type: object
      properties:
        view_data_token:
          pattern: "^([a-zA-Z0-9_=]+)\\.([a-zA-Z0-9_=]+)\\.([a-zA-Z0-9_\\-\\+\\/=]*)"
          type: string
          description: |
            A JWT token where the payload contains the information of the pension and pension illustration data associated with the asset_guid.  The schema for the payload of the token, the view_data_token_payload schema, is provided separately.
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcnJhbmdlbWVudHMiOlt7InBlbnNpb25Qcm92aWRlU2NoZW1lTmFtZSI6Ik15Q29tcGFueSBEaXJlY3QgQ29udHJpYnV0aW9uIFNjaGVtZSIsImFsdGVybmF0ZVNjaGVtZU5hbWVzIjpbe31dLCJwZW5zaW9uUmVmZXJlbmNlIjoic3RyaW5nIiwicG9zc2libGVDb250YWN0UmVmZXJlbmNlIjoic3RyaW5nIiwicGVuc2lvblR5cGUiOiJBVkMiLCJwZW5zaW9uT3JpZ2luIjoiQSIsInBlbnNpb25TdGF0dXMiOiJBIiwicmV0aXJlbWVudERhdGUiOiIyMDE5LTA4LTI0IiwicGVuc2lvbnNTdGFydERhdGUiOiIyMDAzLTEyLTAxIiwic3RhdGVQZW5zaW9uRGF0ZSI6IjIwMTktMDgtMjQiLCJkYXRlT2ZCaXJ0aCI6IjIwMTktMDgtMjQiLCJzdGF0ZVBlbnNpb25NZXNzYWdlRW5nIjoiSSBhbSBhIG1lc3NhZ2UgaW4gRW5nbGlzaCIsInN0YXRlUGVuc2lvbk1lc3NhZ2VXZWxzaCI6Ik5lZ2VzIHluIEd5bXJhZWcgeWR3IGkiLCJjb250cmlidXRpb25zRnJvbU11bHRpcGxlRW1wbG95ZXJzIjp0cnVlLCJwZW5zaW9uQWRtaW5pc3RyYXRvciI6eyJjb250YWN0TWV0aG9kcyI6W119LCJlbXBsb3ltZW50TWVtYmVyc2hpcFBlcmlvZHMiOlt7fV0sImJlbmVmaXRJbGx1c3RyYXRpb25zIjpbe31dLCJhZGRpdGlvbmFsRGF0YVNvdXJjZXMiOlt7fV0sInBvc3NpYmxlTWF0Y2giOnRydWUsImFkbWluaXN0cmF0aXZlRGV0YWlsc05vdEF2YWlsYWJsZSI6dHJ1ZSwiY29udGFjdFNjaGVtZSI6dHJ1ZSwidGVtcG9yYXJ5U3lzdGVtRXJyb3IiOnRydWV9XSwicGVuc2lvbkxpbmsiOiJhc2FkZmVycjM0ZmV2ZXJmIiwicGVpIjoiYXNmZXQ1NDY3Z3NkcmZzZGYifQ.GZCwnsgA73aeoPjB4oMpT5oW7t1bcXim94oN4ADb8Rw
  parameters:
    X-Request-ID:
      name: X-Request-ID
      in: header
      description: A unique correlation id
      required: true
      style: simple
      explode: false
      schema:
        type: string
        format: uuid
        example: 35cfcfb0-d98d-451f-83f1-e59933078555
  securitySchemes:
    rpt:
      type: http
      description: "An RPT token supplied by the dashboard, obtained from the CDA."
      scheme: bearer